### ISSUE TITLE
Supported Platforms?

### ISSUE THREAD

**Issue by NathanCleary123** [microsoft/ProjectAcoustics#119]
Hey, 

Quick question. Which platforms are currently supported with Project Acoustics?

I'm currently developing a game with the aim to release on PC, Mac, Android, iOS and Switch as the main platforms and think I saw a post somewhere about Mobile/Android not being currently supported or it's 'in the works' so I thought I'd ask quickly.

Thanks,
Nathan

**Comment by NoelCross** [comment]
Hello,

Thank you for your interest in Project Acoustics.  Support for various platforms is somewhat hit and miss so I'll try to summarize the platform support we have for now.

PC and Android are currently supported with our Unity and Unreal + Wwise packages available via Microsoft's Download Center.  MacOs is also supported for Unity only.

The plugin that we distribute on the Unreal Marketplace which utilizes Unreal's audio engine is only supported for PC at this time due to limitations for supporting the Source Data Override interface on non-PC platforms.  We are working with Epic to enable an Android offering on the UE Marketplace.  Unfortunately, support for PA on MacOs via the Unreal Marketplace plugin is not currently on list of priorities.

We do not have support for either iOS or Switch at this time.
