### ISSUE TITLE
Project Acoustics and Hololens 2

### ISSUE THREAD

**Issue by cdor8** [microsoft/ProjectAcoustics#121]
Hi, I saw the video from MR Dev Days 2020 covering Project Acoustics on Hololens, I was wondering if the current Project Acoustics will still work with the current version of the MRTK and whether it would be possible to have access to this demo project? 
Thank you!

**Comment by NoelCross** [comment]
@cdor8 Thank you for your interest in Project Acoustics and for watching the MR Dev Days 2020 video.  While the demo project we showed did take advantage of MRTK, since then, PA, MRTK and Unity have been rapidly evolving and we haven't tested everything together since that presentation.  While we don't know of any particular issues, there have been challenges with getting the Newtonsoft dependency shared between these packages to work properly together.

As for sharing of the project, it's incredibly out of date and not really sharable from a sample perspective.  I think that probably the best approach would be for me to connect you with someone on the Mixed Reality developer support team.  If you can share your contact info, then I'll see what I can do to connect you with them.

**Comment by cdor8** [comment]
Hi Noel,
Is there an email to where I can send you my contact details?

**Comment by NoelCross** [comment]
@cdor8 please send your contact information to mailto:acousticsinquire@microsoft.com and I'll connect you with the MR developer support team.  Thanks!
