### ISSUE TITLE
Why does reverberation occur even when the  absorption is set to 1?

### ISSUE THREAD

**Issue by tachibana222** [microsoft/ProjectAcoustics#122]
Hello everyone.
I ran simulations with different sound absorption coefficients to verify the reverberation time.
As a result, we noticed that reverberation occurs even when the sound absorption coefficient is set to 1.
The following is the procedure.

A small enclosed room (10m x 10m x 8m) was created and six walls were set to a sound absorption coefficient of 1.
Simulation Resolution in Probes is set to Coarse.
After local baking, the created ace file was loaded and the audio actor was created in the room.
As a result, RT60 was approximately 1 second.
I had assumed that RT60 would be closer to 0. Will you tell me why this is not the case.

![5setting](https://user-images.githubusercontent.com/115222697/194530240-0f6afe74-e24c-4067-b801-916a77ac80c5.PNG)
Unreal Engine : Version 5.0.3
Project Acoustics : Version 3.0.409

Furthermore, the reverberation time changed when Max Frequency was changed.

RT60
250 Hz → 1.21
500 Hz → 1.21
1000 Hz → 1.69
1500 Hz → 1.52
2000 Hz → 1.60

Is there something wrong with my settings?
Thank you for your cooperation.

**Comment by nikunjragh** [comment]
Nothing wrong with your settings. PA (and most wave solvers) use an impedance boundary condition, which amounts to assuming that the surfaces are locally-reacting. This has the outcome that the direction-dependent response, in your case, is fully absorbing only at when waves strike the walls head-on, but there IS progressively more reflectivity at angled incidence. With locally-reacting surfaces, the reflectivity always increases to full reflection at glancing incidence. So that's why you're not seeing 0s T60. The workaround would be to use the T60 multiplier design control.

The reason for this assumption is computational (baking) cost - modeling "extended reaction" which would absorb more at angled incidence gets progressively more compute-heavy. So we reserve that kind of absorption for the "skybox" on which we use the Perfectly Matched Layer, which is relatively far more expensive but necessary so outdoor areas don't reverberate unrealistically. Local reaction, while not great, is OK for most natural materials since they are solids which have a fair amount of acoustic reflectivity.

The dependence on max frequency should not be happening, thanks for flagging, we will investigate that.

**Comment by tachibana222** [comment]
Thank you for your answer.
I understood that "Absorption" is the Normal incidence sound absorption coefficient.

There's one more thing I'd like to ask you about.
Simulations were performed with a fixed room geometry and maximum frequency (2000 Hz).
The results show that RT60 is smallest when the absorption coefficient is 0.3.
![RT60](https://user-images.githubusercontent.com/115222697/194682908-803c8cb1-8594-416c-92db-403518baa70e.PNG)

There seems to be no correlation between absorption coefficient and RT60.
Is this also an effect of oblique incidence?
I was hoping for a similar trend to the RT60 obtained from Sabine's Formula. Is this difficult to achieve?

**Comment by tachibana222** [comment]
Thank you for your answer.
I understood that "Absorption" is the Normal incidence sound absorption coefficient.

There's one more thing I'd like to ask you about.
Simulations were performed with a fixed room geometry and maximum frequency (2000 Hz).
The results show that RT60 is smallest when the absorption coefficient is 0.3.
![RT60](https://user-images.githubusercontent.com/115222697/194683023-ebb502a1-050a-48d4-baa8-8e29920fdb6d.PNG)


There seems to be no correlation between absorption coefficient and RT60.
Is this also an effect of oblique incidence?
I was hoping for a similar trend to the RT60 obtained from Sabine's Formula. Is this difficult to achieve?

**Comment by nikunjragh** [comment]
That unintuitive trend you're seeing is most probably because the T60 estimation is hitting the solver's numerical noise floor, which is another issue we intend to fix in future. To verify this, it will be useful to also tabulate the wet level in dB that you observe for these cases. That will probably show a nice monotonic trend that you're expecting.

**Comment by nikunjragh** [comment]
Also, these theoretical curves might help paint a picture; not specific to our system, but relating normal to diffuse absorptivity, and to T60 (which is inverse of latter per Sabine). All assuming local reactance (impedance boundary condition).

![image](https://user-images.githubusercontent.com/43619513/194722289-b112ae2e-9117-4650-b651-ac4e279b46fe.png)

**Comment by tachibana222** [comment]
Thanks for the detailed information.
As you mentioned, there was a good correlation between wetness and absorption.
Using a cubic room was not a good choice. I will create a room like a reverberation room for further verification.
Thank you very much.

**Comment by nikunjragh** [comment]
For our records, it would be helpful for us if you can share the wetness values for the table you had shared above. Its OK if you can't.

**Comment by tachibana222** [comment]
![wetness](https://user-images.githubusercontent.com/115222697/194784616-e5c39218-986d-4788-afa4-6f1e9cd200d1.PNG)
I hope this will help.

**Comment by nikunjragh** [comment]
yep it does, thanks much!
