### ISSUE TITLE
Query acoustics performance variations

### ISSUE THREAD

**Issue by HDalsfelt** [microsoft/ProjectAcoustics#134]
Hi!
I'm testing project acoustics in our game and it sounds really great. However, there are some variations in performance that I would like to ask you about. E.g when standing at one position the average time for a call to QueryAcoustics is ~0.007ms, then taking two steps forward the average query time goes to ~0.02ms (the same samples are playing, ambience stuff).
I wonder if you have any idea/suggestion on what can cause these performance variations in the query? Probe layout?
The ace-file was baked locally with coarse setting.

**Comment by MikeChemi** [comment]
To start off: these numbers match what I'd expect. So that's a relief :)

To answer your question, there's a lot of stuff that goes on internally every query. Since it sounds like you're in a steady state (take a few steps then sit and watch the perf counters for awhile then take a few more steps), my guess is that the number of probes being used for interpolation is different depending on where you're standing. For example, if you're standing right on top of a probe, the query will finish much faster than if you're standing in the middle of four probes.

**Comment by HDalsfelt** [comment]
Thanks, I understand. Seems strange that it's very  "on-off" at certain places in the level. 

Now I noticed now that one thing that's different is that only have one call to "QueryOutdoorness" where it's better performance and there are two calls when it gets worse? I must have done something wrong somewhere.  :)

**Comment by MikeChemi** [comment]
QueryOutdoorness should only be happening once per frame, but there are a few circumstances that might trigger it to be called twice. This is largely due to the async nature of the queries. If the listener moves from frame to frame while sounds are coming/going, we may update the cached listener position in the middle of a frame, causing an extra outdoorness query for that frame.

**Comment by HDalsfelt** [comment]
I made a mistake when I tried to disable acoustics on the server (I think) so PostTick were called twice -> m_IsOutdoornessStale got reset.
