### ISSUE TITLE
Unreal Engine's Movie Render Queue crashing when Source Data Override Plugin is set to Project Acoustics

### ISSUE THREAD

**Issue by aidannewsome** [microsoft/ProjectAcoustics#160]
Hello,

Whenever I try to render a still or sequence using the Movie Render Queue while the Source Data Override Plugin is set to "Project Acoustics," Unreal Engine crashes. I have lots of crash logs I could share if it's helpful. I'm wondering if it's related to the error I posted about earlier, which is #152. What's the best way to proceed? Should I just disable it every time I want to do a render? I am using it in-game, but we'd also like to render sequences/stills from the projects, although the audio for those doesn't matter.

Aidan

**Comment by KyleStorck** [comment]
Could you post the crash logs please

**Comment by aidannewsome** [comment]
Most Recent - [CH_VR_Experience_UE5.log](https://github.com/microsoft/ProjectAcoustics/files/10737160/CH_VR_Experience_UE5.log)

Additional 1 - [CH_VR_Experience_UE5.log](https://github.com/microsoft/ProjectAcoustics/files/10737170/CH_VR_Experience_UE5.log)


Additional 2 - [CH_VR_Experience_UE5.log](https://github.com/microsoft/ProjectAcoustics/files/10737173/CH_VR_Experience_UE5.log)

**Comment by aidannewsome** [comment]
Here's an example of me reproducing the crash - https://share.vidyard.com/watch/kDVQxrMB4PXPBVe8fDmw4h?

**Comment by KyleStorck** [comment]
Thanks for the report. The only thing I see in the logs is it appears that Movie Render Queue is using a buffer size that we don't support. Which means that our plugin doesn't initialize. But it's bad that it causes the editor to crash.

For now, you can disable the plugin for the renders, especially since you don't need audio for them. I'll file a bug and we'll investigate how we can handle this situation better.

![image](https://user-images.githubusercontent.com/1233941/218875246-f8005602-ce7e-41d0-8af3-a4f704d40e1b.png)

**Comment by aidannewsome** [comment]
Thanks, Kyle!

**Comment by NoelCross** [comment]
@aidannewsome circling back to this issue, we did do an update for UE5.2 which hardened some of the initialization paths.  It's possible that we fixed this crashing using in that update, but we haven't confirmed this to be the case.  If this is still happening for you with the latest plugin, please let us know.  We still don't support buffer sizes of less than 256, but hopefully we don't crash anymore.
