### ISSUE TITLE
Does the Project Acoustics Spatial Reverb plugin required Wwise Convolution Reverb plugin to work?

### ISSUE THREAD

**Issue by FabricioMSantos** [microsoft/ProjectAcoustics#168]
I integrated Project Acoustics with the Spatial Reverb plugin following the [guide](https://learn.microsoft.com/en-us/gaming/acoustics/unreal-wwise-integration#project-acoustics-spatial-reverb), but I didn't hear any difference between the Ak Component and the Acoustics audio component until I added the Wwise Convolution Reverb plugin.

This message appears in Wwise 2021 and 2022 after Import Factory Assets
![1](https://user-images.githubusercontent.com/37518637/227303284-28bb6e5c-d709-45d7-af50-8970923d2227.png)

**Comment by BillarySquintin** [comment]
No, as long as you're using the Project Acoustics plugin from the Unreal Marketplace with UE5.0+ you only need the plugin itself, .NET Framework 4.7.2+, and Python. This guide will be more helpful: https://learn.microsoft.com/en-us/gaming/acoustics/unreal-audio-integration

I think the older versions of the project for UE4 required WWise, but since the 2022.1 update and release on the UE marketplace WWise is optional.

**Comment by drewbitllama** [comment]
Hi Fabricio! Thank you so much for trying out our technology! Sorry you've been running into this issue. You don't need a Convolution license in order to use our spatial reverb. To get it to work, make sure you follow exactly the WWISE integration readme steps (https://learn.microsoft.com/en-us/gaming/acoustics/unreal-wwise-integration) and the last step is to make sure you've selected "Spatial Reverb" as the Reverb Type in the Unreal-side plugin options (https://learn.microsoft.com/en-us/gaming/acoustics/unreal-wwise-integration#audio-setup-in-unreal). Best of luck, cheers!

**Comment by drewbitllama** [comment]
Note that you don't need to follow the Convolution setup guide unless you want to use stereo reverb instead of the spatial reverb.

**Comment by UserProfileAccountName** [comment]
Ok, thanks for the help!
