### ISSUE TITLE
PIE crash when loading 2 clients

### ISSUE THREAD

**Issue by SeanGaravan** [microsoft/ProjectAcoustics#186]
Hello, I'm using PA spatialisation (both spatialisation and reverb are set to PA in project settings) and finding that if I start PIE with 2 clients I will crash each time, however if I load with 1 client and then load another client whilst already in PIE then I don't crash. 
I'm on UE5.2.
So the only way I crash editor is with 2 PIE clients when I've enabled run under one process.
I can run 1 client and then load another client with run under one process enabled without crashing. 
I can run 2 clients with run under one process is disabled and thats fine as well, no crashes. 

Many thanks!

**Comment by KyleStorck** [comment]
Running multiple clients in PIE is not a supported scenario with Project Acoustics. The fact that you are seeing it not fail when the 2 clients are not under the same process is expected. Problem happens when multiple clients are under the same process, the UE audio engine re-uses the same audio IDs and we don't handle that yet.
