### ISSUE TITLE
Unity + FMOD / Wwise

### ISSUE THREAD

**Issue by ThePCJakub** [microsoft/ProjectAcoustics#5]
Dear Sir / Madam,

I have just recently found out about Project Acoustics and it seems like a very robust and useful system.

However, I would like to ask, whether it is possible to use this package in combination with Unity and an Audio Middleware like FMOD or Wwise.
I have seen somewhere on the project page, that it is possible to integrate it with Wwise & Unreal.
Is there any possibility to use Project Acoustics with Unity + FMOD or Wwise?

Best regards,
Jakub.

**Comment by NoelCross** [comment]
Jakub,

Currently, Microsoft hasn't released a Project Acoustics solution for Unity + FMOD or Wwise  yet.

We have recently started a conversation with a partner that is also looking for Unity + FMOD support.  They are interested in developing this plug-in combination themselves and sharing the solution back with Microsoft in order to us to distribute publicly.  Hopefully we'll have something ready in the next couple of months for Unity + FMOD.

We also have been working a version of Project Acoustics working with Unity + Wwise internally, but we haven't released it publicly yet.  We could look at sharing this solution with you in an beta state if you are interested.

Send me an email at noelc@microsoft.com and we can discuss logistics for getting you enabled.

Thanks,
Noel

**Comment by NoelCross** [comment]
Exciting news on the plug-in front, we've opened up a new GitHub repo for our Unity plug-in.  There's two versions of plug-ins currently available:

1. The primary plug-in code is for HoloLens 2 projects to have access to the spatial audio hardware acceleration support available on HoloLens 2.  This plug-in will also work on Windows and XBox platforms as it uses the ISpatialAudioClient API.

https://github.com/microsoft/spatialaudio-unity

2. Another plug-in source that we are providing is the source for a native Unity plug-in which utilizes two DLLs for rendering.  To be fully functional, it requires the Project Acoustics libraries to be present -- both HrtfDsp.dll and Triton.dll.  This set of code could be the basis for an FMOD plug-in as it illustrates the call pattern for using the acoustic simulation and the spatial audio rendering components included in Project Acoustics.

https://github.com/microsoft/spatialaudio-unity/tree/develop/Source/Spatializer/ProjectAcoustics

The partner we were working with on the FMOD port might not be able to give Microsoft the code back.  They are using this second sample as a starting point for this porting exercise.  It's possible that you could also start with this offering.

Microsoft is not actively working on an FMOD solution at time, but we are working on making more of our plug-ins available on open source to allow for enabling more platform support.

**Comment by kegodin** [comment]
Thanks for filing this issue. 

For FMOD request: Duplicate issue is https://github.com/microsoft/ProjectAcoustics/issues/4

For Wwise support: Please email noelc@microsoft.com as described above.

Resolving 'closed'. Please reopen, or open another issue, with comments/concerns/questions. Thanks!
