### ISSUE TITLE
What effects are modeled? 

### ISSUE THREAD

**Issue by aluo-x** [microsoft/ProjectAcoustics#60]
I'm currently looking at several spatial audio engines for an academic project, and I'm trying to understand just what this project models.

For example as I understand for Steam Audio
* Assumes instantaneous sound propagation
    * No distance based delay
    * Any delay is from the HRTF, presumably measured at 1m
    * Does have distance based decay
* Ray traced (specular?) reflections
* No near-field special code path
    * Google Resonance & FB 360 have special code paths on very close sound sources (<1m?)

I guess my question for microsoft PA:
1. Does it model propagation delay (distance/(343m/s))? Does it assume that different frequencies propagate at the same speed?
2. Does it model interaural time differences?
3. Is the distance based decay curve frequency dependent? Can we access the parameters for the curve?
4. Can we modify the HRTF? Or if not, can we read the default HRTF? Or else, is microsoft using a HRTF derived from CIPIC? 
5. Is there a special code path for close sound sources? Or does it simply extend the 1/r^2 decay to the near field? 
6. Where can I find a detailed documentation? Or a design doc? 

Edit: random typos

**Comment by MikeChemi** [comment]
Hi @aluo-x ! Thanks for the questions. At its core, Project Acoustics is a combination of an acoustics simulator with HRTF rendering. There are other rendering options, but it's easier to answer your question with this default configuration in mind.

1. Yes, propagation delay is modeled at a constant speed.
2. Yes, the HRTF renderer reproduces ITDs.
3. No. This is an active area of research for us.
4. No on all counts, sort of. You can change the dry path rendering (the HRTF) using the Wwise integration. However, that HRTF change is not through the Project Acoustics plugin itself. Rather, the Wwise project can be set up to bypass the Project Acoustics plugin rendering on the dry path, allowing you to insert any other plugin that you want.
5. We do have near-field filtering, yes.
6. Plugin documentation is available at http://aka.ms/acoustics . If you'd rather read the technical details, you can find the latest publications on the research sites: https://www.microsoft.com/en-us/research/project/project-triton/ and https://www.microsoft.com/en-us/research/project/spatial-audio/ . Note that not all the research linked is available in Project Acoustics today, although most topics are on our roadmap for future releases.

**Comment by aluo-x** [comment]
Thanks for the clarification. The comments are immensely helpful. 

On 4 in particular, I guess it should be possible to simulate impulses on a mid-field sphere w/o reflection and recover the HRTF, so in practice this is not a problem. 

On 5, can you comment more on the near field filtering? I'm assuming this is correcting for the "parallax" w.r.t. to the ears, and possibly some additional shadowing model? 

The papers you reference (on project triton in particular) are very helpful for understanding how the system could work at a broad level. I'm mainly concerned with how realistic the audio produced by PA is compared to the real world - what do we account for - what simplifying assumptions are made - how consistent the system is with itself. I will definitely take a look at the papers.

I was wondering if there is a way to read the source of PA. Source access is not critical for my task, since I'm primarily interesting in using PA to synthesize simulated data. But knowing that a simulator is behaving as expected would helpful.

**Comment by nikunjragh** [comment]
Based on what you said about point 4 above - PA does not use impulse responses as the interface between acoustic simulation and spatial audio rendering. This is a big difference compared to Steam Audio (plus we use a wave solver instead of ray tracing). So if you plan to use PA as an acoustic simulator, know that you will only get certain parameters of the acoustic field on the output, not the raw impulse responses. The Unreal+Wwise integration shows this transparently: the acoustic simulation data is queried for the source, and then processed and passed to Wwise for rendering.

RE: technicalities: 
- The 2014 SIGGRAPH "Parametric wave field coding..." paper is the core architecture. 
- The shipping PA plugin today is close to the 2018 "Parametric directional coding..." paper in the internal parametric data that is available. 
- In a few days, we'll be posting the webinar I gave on this to youtube [on this page](https://www.microsoft.com/en-us/research/video/interactive-sound-simulation-rendering-immersive-soundscapes-in-games-and-virtual-reality/). The second half talks about Triton's (the research project behind PA) high-level architecture, motivations, strengths/limitations, etc. which will help you get oriented.

Also, for point 3 - I think you _could_ model distance attenuation depending on frequency simply by using an RTPC in Wwise to hook up our output delay (times C) to an equalization filter in Wwise. It will require some code but nothing too complicated, pretty much on the lines of what we have already.

**Comment by MikeChemi** [comment]
About the near field filter -- yes, you have the intent of it correct.

About source access -- we have a source licensing program available through [Microsoft's Game Developer Kit](https://docs.microsoft.com/en-us/gaming/acoustics/what-is-acoustics#source-access) program.

**Comment by aluo-x** [comment]
@nikunjragh I appreciate the response. I read through the 2014 paper and it was very helpful (Acoustic reciprocity is very surprising and still non-intuitive!), currently working through the 2018 paper - it is quite a bit more dense. I watched your video as well, it was great in giving an overview.

@MikeChemi Since this is an academic project, who would be the "Microsoft Gaming representative"? Would be nice to have the wave simulator and the bits not related to parametric compression (beyond just the spatializer) open source in the future!

**Comment by MikeChemi** [comment]
At this time, our only source licensing program is via the game developer program. We don't have plans to open source any part of the simulator at this time.

**Comment by aluo-x** [comment]
Understood. For an academic project who would be the "Microsoft Gaming representative"?

**Comment by nikunjragh** [comment]
Hi @aluo-x - Currently we do not have an academic source licensing program. The program Mike mentioned is for game studios. That said, others have made this request as well and an academic license is something we are thinking about, although we can't promise anything right now. If possible, email me directly and share the following information: your name, university/group & any info about your research project and how you see PA helping. This is valuable input that will feed into our decision making in the future. My email is nikunjr at microsoft dot com.

**Comment by aluo-x** [comment]
Thanks for the response @nikunjragh. I've sent an email with my affiliation & project description. A programmatic way to access the raw impulse responses (ideally in Unity) would be sufficient to satisfy my project requirements.

I'm closing this issue for now. 

Appreciate all the technical details @MikeChemi @nikunjragh!
