### ISSUE TITLE
How to create local baking scene in UE4 project

### ISSUE THREAD

**Issue by eefan000** [microsoft/ProjectAcoustics#61]

**Comment by NoelCross** [comment]
Hello @eefan000 , 

Local baking for UE4 isn't a mainline supported scenario, but it is possible to accomplish with a little bit of effort.

You'll mostly be following the instructions for [local bakes for Unity](https://docs.microsoft.com/en-us/gaming/acoustics/unity-baking#Local-bake) which requires installing Docker.

Since we don't generate the script file for you to run in UE, you'll need to run the following command after doing the pre-bake process in UE:

`docker run --rm -w /acoustics/ -v \"%CD%\":/acoustics/working/ {baketoolsURL} ./tools/Triton.LocalProcessor -vox {yourvoxfile.vox} -config {yourconfigfile.xml} -workingdir working 
`

You might need to search around in your filesystem to find the generated VOX and XML files to feed into this command.

**Comment by MikeChemi** [comment]
Local baking in UE is supported in the 3.0 release, available now!
