### ISSUE TITLE
Multiple precompiled assemblies with the same name Newtonsoft.Json.dll

### ISSUE THREAD

**Issue by AndyPipe** [microsoft/ProjectAcoustics#65]
(Assets/Acoustics/Editor/Plugins/Windows/Newtonsoft.Json.dll)
.../Library/PackageCache/com.unity.nuget.newtonsoft-json@2.0.0/Runtime/Newtonsoft.Json.dll)
empty initial unity project merely, play mode can't be entered, compile errors
it is as in unity.plugin so is in wwise.beta.

Is there a short temporary way to solve this to explore PA?

**Comment by KyleStorck** [comment]
Hi @AndyPipe. We are aware of this issue but don't have a fix yet. I believe a common workaround for this is to simply delete one of the conflicting .dlls.

**Comment by MikeChemi** [comment]
What Unity version are you using? It's concerning that you're seeing this in a blank project. We've seen this issue pop up when combining PA with other plugin packages, but not in a blank project.

**Comment by Glokta0** [comment]
To add some information to this thread: 
I'm having the same issue, because other packages (i.e. https://github.com/siccity/gltfutility.git, com.unity.collab-proxy) define their dependency in packages-lock.json:
```
      "dependencies": {
        "com.unity.nuget.newtonsoft-json": "2.0.0"
      },
```

If I simply don't import the dll from the Acoustics package, the errors like the following show up in its place:
```
Assembly 'Assets/Acoustics/Editor/Plugins/Windows/Microsoft.Azure.Batch.dll' will not be loaded due to errors:
Microsoft.Azure.Batch references strong named Newtonsoft.Json Assembly references: 10.0.0.0 Found in project: 12.0.0.0.
Assembly Version Validation can be disabled in Player Settings "Assembly Version Validation"
```

I'm not sure if disabling the Assembly Version Validation may do the trick as a quick work around for some people. It doesn't seem the way to go long term.

I believe collab is activated by default from some unity version onward - which may explain why people are reporting it in blank projects, too?

**Comment by Xapu1337** [comment]
Facing same issues...

**Comment by joelmpeel** [comment]
I am also having the same issue...I tried removing the redundant Newtonsoft.Json.dll and I also get the same issue as Glokta0 when doing this. I have also tried deleting the dll's corresponding to Azure and I get further errors when doing this. I am using 2021.2.11f1

**Comment by ashtat** [comment]
@Larzone24 Try renaming the Newtonsoft,json.dll in the plugin folder (under "Assets\Acoustics\Editor\Plugins\Windows")  to something like "PA.Newtonsoft.Json.dll" which should address the issue. Unity should still find and load the assembly correctly (thanks to strong name binding) so shouldn't affect any functionality either.

**Comment by NoelCross** [comment]
With the PA3.0 release, this Newtonsoft collision should be addressed now.  Please let us know if you are still experiencing issues.

**Comment by V0odo0** [comment]
Unity 2022.1.1f.
![image](https://user-images.githubusercontent.com/10213769/170613928-2b07da21-f68a-4414-bba8-538710cdd012.png)

**Comment by NoelCross** [comment]
@V0odo0 Thank you for the feedback.  It looks like you are hitting something that we more or less worked around in the sample scene and you'll need to make a similar change in your project in order to avoid this issue.  If you modify the Player settings for "Assembly Version Validation" to off, you should no longer see this issue.  We didn't notice any other drawbacks to disabling this validation, but there might be issues lurking that we are not aware of.

<img width="217" alt="image" src="https://user-images.githubusercontent.com/19439257/172028774-e1feb229-a6fa-48ca-b744-0031bc60de14.png">

**Comment by V0odo0** [comment]
> @V0odo0 Thank you for the feedback. It looks like you are hitting something that we more or less worked around in the sample scene and you'll need to make a similar change in your project in order to avoid this issue. If you modify the Player settings for "Assembly Version Validation" to off, you should no longer see this issue. We didn't notice any other drawbacks to disabling this validation, but there might be issues lurking that we are not aware of.
> 
> <img alt="image" width="217" src="https://user-images.githubusercontent.com/19439257/172028774-e1feb229-a6fa-48ca-b744-0031bc60de14.png">

I just reopened my test project and noticed that the error magically disappeared. That is with Assembly Version Validation checked in Player Settings and Auto Reference unchecked for PA.Newtonsoft.Json. The project has nothing but Acoustics package imported.

Prior to this, the error still persisted even with Auto Reference unchecked for PA.Newtonsoft.Json. As far as I remember Editor restart didn't help either.

Kinda strange but rebooting might was the problem solver in my case.
