### ISSUE TITLE
Out of interest, what method does PA use to render soundscape? is it FDTD or Finite element method? 

### ISSUE THREAD

**Issue by Danreeves12** [microsoft/ProjectAcoustics#73]

**Comment by nikunjragh** [comment]
@Danreeves12 Neither. It is a spectral solver called "adaptive rectangular decomposition". If you're curious, here's a [PDF](http://www.nikunjr.com/Projects/ARD/ARD.pdf) describing the main ideas.

**Comment by Danreeves12** [comment]
Very interesting. Thank you for commenting :)

**Comment by nikunjragh** [comment]
No prob, this is something I love to do, happy to see when someone is curious :). The core idea in one line is to decompose the world's air into rectangular air partitions (bigger the better) because for each rectangle, you can do nearly error-free propagation since the solution to the wave equation (the Green's function) is known - the errors are limited to where these rectangles meet (the "interfaces").  Upshot is simply that one can do coarser grids which goes much faster.
