### ISSUE TITLE
ContainerInvalidImage on Azure Nodes Standard F8s_v2

### ISSUE THREAD

**Issue by mozahzah** [microsoft/ProjectAcoustics#76]
Hello Im not able to bake, my nodes turn to unusable and spit the following error. 

![image](https://user-images.githubusercontent.com/37258667/147298067-ded5bf59-e795-4a79-98a9-ae1f108e92fc.png)
operating system: microsoft-azure-batch ubuntu-server-container 20-04-lts (latest)

**Comment by NoelCross** [comment]
@mozahzah we've been able to reproduce this issue on our end and it appears to be an issue with the Microsoft Container Registry which hosts the Docker images for the toolset.  We are following up with the Microsoft Container Registry devs to figure out the root cause of this issue.  We'll let you know as soon as we find anything out.

**Comment by NoelCross** [comment]
@mozahzah it appears that there has been a change to the way the container image name is parsed that we are looking into.  Please update the Toolset Version in the Azure Configuration settings to specify a lower case "M" for the word Microsoft.

e.g.: mcr.**m**icrosoft.com/acoustics/baketools:2.0.143_Linux

This update to the parameters should allow Azure Batch to pull the image from the Microsoft Container Registry (MCR) correctly.  Sorry for the inconvenience.

**Comment by mozahzah** [comment]
@NoelCross Thank you for taking the time to investigate! appreciate it!
