### ISSUE TITLE
Unity not showing Acoustics in the window tab.

### ISSUE THREAD

**Issue by Aakriti05** [microsoft/ProjectAcoustics#84]
I have loaded the project acoustics as custom package and followed all steps in the tutorial. But "acoustics" option is not showing in the window tab. Screenshot below. Can anyone help me?
![WhatsApp Image 2022-04-26 at 13 49 03](https://user-images.githubusercontent.com/20537799/165361478-7b21d955-486f-4f5b-a2f0-2c0a0fc902a6.jpeg)

**Comment by NoelCross** [comment]
@Aakriti05 there's usually a message in the console window providing insight into what the problem is.  If the message is about a conflict with Unity's version of Newtonsoft assembly, a workaround that we've found is to rename "Newtonsoft.Json.dll" to "PA.Newtonsoft.Json.dll" from the Project Acoustics package.  We plan on releasing an update in May that'll address this issue.

**Comment by Aakriti05** [comment]
I initially got the "Newtonsoft.Json.dll" error. But after restarting unity it went away. I am using unity 2020.x
Should I try unreal if that is more stable ?

**Comment by NoelCross** [comment]
Switching to Unreal Engine is an option as well, although the full solution at this point requires Wwise as the audio engine.  We do plan on releasing a version of PA for Unreal that doesn't require Wwise.  Stay tuned for updates on that offering.

**Comment by Aakriti05** [comment]
The above idea solved the issue. Thanks!
