### ISSUE TITLE
Errors on Audio Source when heard through a wall

### ISSUE THREAD

**Issue by admsyn** [microsoft/ProjectAcoustics#99]
I get the following errors on the stats display whenever I leave the room in which my audio source is located.

> Found samples but discarded after reading param field and contrast hack

> Parameter compute failed for all probes. Returning default

![image](https://user-images.githubusercontent.com/609318/174271155-09d7ed16-adbf-4864-b04e-9a63b71a1166.png)

If I'm in the room:

![image](https://user-images.githubusercontent.com/609318/174271529-9b77063d-865c-4292-9f75-66fe242fe951.png)

The way this area is laid out, the room is fully enclosed (closed door, no open windows etc). Once I leave that closed room the errors occur.

Setup:
- UE 5.0.2
- Local Bake
- Unreal Audio

**Comment by MikeChemi** [comment]
If I understand your scene layout correctly, this is currently the expected behavior. If there are no open-air paths connecting the listener location to the source location, the acoustic query will fail. These errors are showing the specifics of why the query failed -- all samples discarded, because none of them were valid, because the source is unreachable from the listener.

**Comment by admsyn** [comment]
That makes sense, thank you.
